- name: 'Qodana Scan'
  uses: JetBrains/qodana-action@main
  env:
    QODANA_TOKEN: ${{ secrets.eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiIza05vbSIsInByb2plY3QiOiIzMWR3NyIsInRva2VuIjoiQUxaTG8ifQ.rElazOemdKGFkXSaqCrOSP9qG3WcdD8aePEgw5Ri-T8}}
